name: dicee
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  material_color_utilities: ^0.11.1
  vector_math: ^2.1.4
  vm_service: ^14.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/
